version: '3.0'
services:
  website:
    container_name: website
    build:
      # defines build parameters. Not necessary because we have everything in root at the moment
      dockerfile: ./Dockerfile
      context: ./website
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file: .env
  nginx:
    container_name: nginx
    build:
      dockerfile: ./Dockerfile
      context: ./nginx
      args:
        DEV: "true"
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    env_file: .env
