version: '3.0'
services:
  website:
    container_name: website
    build:
      # defines build parameters. Not necessary because we have everything in root at the moment
      dockerfile: ./Dockerfile
      context: .
      args:
        DEV: "true" # swaps nginx file for local development
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    env_file: .env
    
